/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e225754;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("Hello, World!");
    }
}